# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"init_func": "00_models.ipynb",
         "layer_types": "00_models.ipynb",
         "extract_layer": "00_models.ipynb",
         "FlexConvLayer": "00_models.ipynb",
         "init_default": "00_models.ipynb",
         "FlexUnetEncoder": "00_models.ipynb",
         "FlexUnetDecoder": "00_models.ipynb",
         "SUNET": "00_models.ipynb"}

modules = ["Models.py"]

doc_url = "https://habib.s.t.bukhari.github.io/nbdev_template/"

git_url = "https://github.com/habib.s.t.bukhari/nbdev_template/tree/master/"

def custom_doc_links(name): return None
